### ISSUE TITLE
No Sat icon in my osd

### ISSUE THREAD

**Issue by GJMedia** [Kw0ngk4n/WS-Neue#1]
Hi, first thing thx you for your work!!!

I have some trouble in my WS Goggles, i dont have Sat icon and number on my OSD

**Comment by Kw0ngk4n** [comment]
This is probably caused by newer versions of Betaflight (4.5+) sort of "requiring" 4 page HD font for the "color" function, I will add a 4 page edit of current release as a fix, no new version number would be added.
